first = input("Enter proper noun: ")
second = input("Enter plural noun: ")
third = input("Enter pronoun: ")
fourth = input("Enter verb ending in 'ing': ")
fifth = input("Enter plural noun: ")
sixth = input("Enter noun: ")
seventh = input("Enter verb ending in 'ing': ")
eighth = input("Enter adjective: ")

print ( first + ' is the corporate director of a company that creates ' + second + '.')
print ( third + ' does this by ' + fourth + ' a bunch of ' + fifth + ' into a big ' + sixth)
print (' and then ' + seventh + ' them.')
print ('this makes the product so ' + eighth + '!')
